---
title: "Interpretation for ALL dataset SRP056295 (Pabst, Blood, 2016)"
author: "Mustafa AbuElqumsan and Jacques van Helden"
date: '`r Sys.Date()`'
output:
  pdf_document:
    fig_caption: yes
    highlight: zenburn
    toc: yes
    toc_depth: 3
  html_document:
    fig_caption: yes
    highlight: zenburn
    theme: cerulean
    toc: yes
    toc_depth: 3
    toc_float: true
  word_document: default
  bookdown::html_document2: default 
# bibliography: Bibliography.bib
biblio-style: "apalike"
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, fig.path = "figures/")

```

We look forward to make the quantitative summary for some critical values and parameters, which are summaried as in the follwing table 

```{r quantitative summary}
qunt.sammay <- data.frame( "recountID" = parameters$recountID,
                           "Descrip.dataset" = parameters$classColumn,
                           "no.runs" = length(loaded$runPheno$run),
                           "No.samples before filtering" = length(loaded$runPheno$sample),
                           "No.genes before filtering" = nrow(loaded$countsPerRuns),
                           "No.genes NA vlues" = loaded$filteredData$naGenes,
                           "No.genes zero.variance" = length(loaded$filteredData$zeroVarGenes),
                           "No.genes kept filtering" = length(loaded$filteredData$keptGenes),
                           "selected classes" = data.frame(loaded$filteredData$selectedClasses),
                           "No.classes" = length(unique(loaded$filteredData$classes)),
                            "Nosamp per.class"= table(loaded$samples.per.class)
                           )

kable(qunt.sammay)
```

