---
title: "Recount exploration"
author: "Mustafa AbuElQumsan and Jacques van Helden"
output:
  html_document:
    code_folding: hide
    fig_caption: yes
    highlight: zenburn
    self_contained: yes
    theme: cerulean
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    fig_caption: yes
    highlight: zenburn
    toc: yes
    toc_depth: 3
  word_document: default
date: '`r Sys.Date()`'
editor_options: 
  chunk_output_type: console
---

```{r knitr_setup, include=FALSE,  eval=TRUE, echo=FALSE, warning=FALSE}
library(knitr)
knitr::opts_chunk$set(
  fig.path="figures/",
  echo=FALSE, 
  eval=TRUE, 
  cache=FALSE, 
  message=FALSE, 
  warning=FALSE)
library(recount)
library(SummarizedExperiment)
```


## General exploration of the metadata table

```{r}
min.samples.per.class <- 10


recount.subsets <- c("sra", "gtex", "tcga") ## Supported values for recount subset attribute
recount.subset <- "sra" ## For the time being we work with SRA (Short Read Archive database)

recount.metadata.sra <- all_metadata(subset='sra')
recount.metadata.gtex <- all_metadata(subset='gtex')
recount.metadata.tgca <- all_metadata(subset='tcga')

recount.metadata <- recount.metadata.sra
# View(as.data.frame(recount.metadata))
# names(recount.metadata)
dim(recount.metadata)

summary.per.col <- data.frame()
for (column in names(recount.metadata)) {
  
  col.stats <- data.frame(
    "column" = column,
    "unique.values" = length(unique(recount.metadata[, column]))
    )

    summary.per.col <- 
    rbind(summary.per.col, col.stats)
                            
}
summary.per.col

kable(summary.per.col)

```


## Filtering out the NA values

```{r}
metadata.nona <-  asS4(na.omit(recount.metadata))
##metadata.nona$project <-as.list(metadata.nona$project)
message("the dimension of the metadata.nona is :"  )
dim(metadata.nona)
message("a dimension of the Recount metadata is:")
dim(recount.metadata)

## count the number of projects with no NA value
nona.projects <- unique(metadata.nona$project)
message("Great, there are ", length (nona.projects), " projects with no NA value. ")

## Count th number of distinct classes (characteristics) for each project
length(nona.projects)

x <- metadata.nona[project == nona.projects, ]
dim(x)
View(as.data.frame(x))
recount.metadata.nona <- recount.metadata[ ,]
dim(recount.metadata.nona)
View(as.data.frame(recount.metadata.nona))

new.selected.project <- data.frame()
metadata.names <-names(metadata.nona)
if (is.null(nona.projects) || length(nona.projects) < 1) {
  message("There are no meta data for such project")
} else  {
  pro <- 1
  
  for (pro in 1:length(nona.projects)) {
     selected.project  <- metadata.nona$project[pro]
     new.project <- subset(metadata.nona, project == selected.project)
     new.project$sample.nb <- length(unique(new.project$sample))
     new.project$geo.acc.nb <- length(unique(na.omit(new.project$geo_accession)))
     new.project$characteristic.nb <- length(unique(new.project$characteristics))
     if( pro ==1 ){
       new.selected.project <- data.frame(new.project)
     } else {
       new.selected.project <- rbind(new.selected.project, new.project )
     } # end else 
  } # end for
}

new.selected.project<- asS4(new.selected.project)


## Select projects with at least 3 classes
x <- subset(new.selected.project,  new.selected.project$characteristic.nb > 3)

## Select projects with precisely 2 classes

## Select projects where there are at least 2 classes with the user-specified min number of samples (parameter previously defined)


View(as.data.frame(metadata.nona))

```


## Exporation of a problematic dataset (with NA values in the characteristics column)



```{r}
library("IRanges")
## In the future, we wold like to understand why some GSE do work andother ones not
# abstract_search(recountID)
project_info <- abstract_search('GSE32465') ## This one works
# project_info <- abstract_search('GSE58135') ## Supposedly breast cancer
recountID <- project_info$project

## Select a Recount ID
recountID <- "SRP003611"
studyPath <- paste0("~/test_recount/",recountID)
dir.create(studyPath, recursive = TRUE, showWarnings = FALSE)
# dir.exists(studyPath)
# list.files(studyPath)


## TO DO for Mustaa: adapt the 2 lines bore in order to ensure that you get the right GSE for the recountID
selectedGSMs <- as.vector(unlist(subset(recount.metadata, project == recountID, select="geo_accession")))

## project_info <- abstract_search(selectedGSMs[1]) ## Does not work with GSM instead of GSE

## Download data from Recount
url <- download_study(recountID, outdir = studyPath)

## Load data
rseFile <- file.path(studyPath, "rse_gene.Rdata")
load(rseFile)
colData(rse_gene)
## hereafter are just the classes for each project
View(as.data.frame(rse_gene@colData@listData$characteristics@unlistData))
length(rse_gene@colData@listData$characteristics@unlistData)
row.names(unique(rse_gene@colData))
colnames(rse_gene)
View(as.data.frame(rse_gene))

# to retrieve the raw count Table
# View(assay(rse_gene))


# explore the pheno Table
rse_gene[, rse_gene$characteristics@elementMetadata]
rse_gene$characteristics@metadata
rse_gene$characteristics@partitioning
rse_gene$characteristics@unlistData
rse_gene$characteristics@elementType


names(colData(rse_gene))
find_geo()
x <-sapply(colData(rse_gene)$run[1:2], find_geo)
View(as.data.frame(x))
length(unique( colData(rse_gene)$project))
length(unique(colData(rse_gene)$experiment))
length( unique(colData(rse_gene)$run))
table( unique( colData(rse_gene)$characteristics))
Na.characteristics <- sum( is.na(colData(rse_gene)$characteristics))

# To explor which regions we are interest 
rowData(rse_gene)
rowRanges(rse_gene)

# Experiment-wide metadata
metadata(rse_gene)

# How to subsetting the SE
rse_gene[1:5 , 1:4]
rse_gene[, rse_gene$characteristics != "NA"]


## put the code to extract the pheno table from this dataset, and explore it!Are there several interesting columns tere ? 

## Count samples for this project
selected.project.metadata <- subset(recount.metadata, project == recountID)
dim(selected.project.metadata)
sample.nb <- length(unique(selected.project.metadata$sample))
geo.acc.nb <- length(unique(na.omit(selected.project.metadata$geo_accession)))
characteristic.nb <- length(unique(selected.project.metadata$characteristics))
message(sample.nb, " samples, ", geo.acc.nb, " non-NA geo accession numbers, ", "classes Number:", characteristic.nb  )

```


