name: rnaseqmva
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - r-base=4.4.0
  - r-essentials
  - r-markdown
  - r-yaml
  - r-roxygen2
  - r-dplyr
  - r-rcurl
  - r-xml
  - r-rcpp
  - r-devtools
  - r-caret
  - r-class
  - r-broom
  - r-e1071
  - r-foreach
  - r-doparallel
  - r-randomforest
  - r-pheatmap
  - r-scatterplot3d
  - r-biocmanager

  # Bioconductor (current)
  - bioconductor-deseq2
  - bioconductor-limma
  - bioconductor-edger
  - bioconductor-vsn
  - bioconductor-derfinder
  - bioconductor-recount
  - bioconductor-s4vectors
  - bioconductor-genomeinfodb
  - bioconductor-summarizedexperiment
