name: rnaseqmva-2025
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - r-base=4.4.1
  - r-essentials
  - r-markdown
  - r-yaml
  - r-roxygen2
  - r-dplyr
  - r-rcurl
  - r-xml
  - r-rcpp
  - r-devtools
  - r-caret
  - r-class
  - r-broom
  - r-e1071
  - r-foreach
  - r-doparallel
  - r-doMC
  - r-randomforest
  - r-pheatmap
  - r-scatterplot3d
  - r-biocmanager
  - r-knitr
  - r-tidyr
  - r-mass
  - r-lattice
  - r-ggplot2
  - r-optparse

  # Bioconductor (current)
  - bioconductor-iranges
  - bioconductor-deseq2
  - bioconductor-limma
  - bioconductor-edger
  - bioconductor-vsn
  - bioconductor-derfinder
  - bioconductor-recount
  - bioconductor-s4vectors
  - bioconductor-genomeinfodb
  - bioconductor-summarizedexperiment
