################################################################
## Define some recurrent tasks

targets:
	@echo "Targets"
	@echo "	parameters		display the general parameters"
	@echo "	convert_pc_plots_all_study_cases	convert PC plots from pdf to ${IMG_FORMAT} for all study cases"
	@echo "	sync_pc_plots_all_study_cases	synchronize PC plots from workspace to the manuscript folder"

# SRP035988 SRP042620 SRP056295 SRP057196 SRP061240 SRP062966 SRP066834
IMG_FORMAT=png
WORKSPACE=~/RNAseqMVA_workspace
STUDY_CASES=`ls -1 ~/RNAseqMVA_workspace/results/  | grep SRP | xargs`
parameters:
	@echo "Parameters"
	@echo "	IMG_FORMAT	${IMG_FORMAT}"
	@echo "	STUDY_CASES	${STUDY_CASES}"
	@echo "	STUDY_CASE	${STUDY_CASE}"
	@echo "	PCS		${PCS}"
	@echo "	MANUSCRIPT_DIR	${MANUSCRIPT_DIR}"
	@echo "	FIGURE_ELEMENTS	${FIGURE_ELEMENTS}"

################################################################
## Convert PC plots from pdf (generated by R) to some other image format
STUDY_CASE=SRP042620
PCS=PC1to4
SOURCE_PLOT=${STUDY_CASE}_log2norm_${PCS}.pdf
SOURCE_PC=${WORKSPACE}//results/${STUDY_CASE}/visualization_of_PCs/${SOURCE_PLOT}
MANUSCRIPT_DIR=~/Dropbox/Mustafa_AbuElQumsan_shared_folder/scientific/research_project_Mustafa/manuscript_supervised_classif_assessment_RNA-seq/
FIGURE_ELEMENTS=${MANUSCRIPT_DIR}/figure_elements/
TARGET_PC=${FIGURE_ELEMENTS}/${STUDY_CASE}_log2norm_${PCS}.${IMG_FORMAT}
convert_one_pcplot:
	@mkdir -p ${FIGURE_ELEMENTS}
	@convert -flatten -density 300 \
		${SOURCE_PC} ${TARGET_PC}
	@echo "	${TARGET_PC}"

convert_pc_plots_one_study_case:
	@echo "Converting PC plot for study case	${STUDY_CASE}"
	@${MAKE} convert_one_pcplot PCS=PC1-PC2
	@${MAKE} convert_one_pcplot PCS=PC3-PC4
	@${MAKE} convert_one_pcplot PCS=PC1to4


convert_pc_plots_all_study_cases:
	@echo "Converting PC plots"
	@for i in ${STUDY_CASES}; do \
		${MAKE} convert_pc_plots_one_study_case STUDY_CASE=$${i}; \
	done




sync_one_pcplot:
	@mkdir -p ${FIGURE_ELEMENTS}
	rsync ${SOURCE_PC} ${FIGURE_ELEMENTS}/


sync_pc_plots_one_study_case:
	@echo "Syncing PC plot for study case	${STUDY_CASE}"
	@${MAKE} sync_one_pcplot PCS=PC1-PC2
	@${MAKE} sync_one_pcplot PCS=PC3-PC4
	@${MAKE} sync_one_pcplot PCS=PC1to4


sync_pc_plots_all_study_cases:
	@echo "Syncing PC plots"
	@for i in ${STUDY_CASES}; do \
		${MAKE} sync_pc_plots_one_study_case STUDY_CASE=$${i}; \
	done

