name: Test Conda RNAseqMVA Env

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda (Miniconda)
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          auto-activate-base: false

      - name: Create environment from YAML
        shell: bash -l {0}
        run: |
          conda env create -f conda-rnaseqmva_2025.yml
          conda activate rnaseqmva-2025
          conda info
          conda list

      - name: Run R tests
        shell: bash -l {0}
        run: |
          conda activate rnaseqmva-2025
          Rscript -e "cat('R version:', R.version.string, '\n')"
          Rscript -e "library(DESeq2); library(recount); library(caret); library(devtools); cat('R packages loaded OK\n')"
